project_id = "bcbrwfochuhylomjgzsl"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.verify-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.register-student]
verify_jwt = false

[functions.register-parent]
verify_jwt = false

[functions.mark-attendance]
verify_jwt = true

[functions.record-result]
verify_jwt = true

[functions.create-class]
verify_jwt = true

[functions.bulk-import-students]
verify_jwt = true

[functions.send-notification]
verify_jwt = true
